# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField(default=18)),
                ('stu_sex', models.BooleanField(default=1)),
                ('stu_birthday', models.DateField()),
                ('stu_create_time', models.DateTimeField()),
                ('stu_score', models.FloatField()),
                ('stu_img', models.ImageField(upload_to='static/images')),
                ('stu_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('stu_eyesight', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
