# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-11 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('pub_date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
