# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0002_auto_20190611_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(db_index=True, max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Questions'),
        ),
    ]
